import groovy.io.FileType

/*
 * This Java source file was generated by the Gradle 'init' task.
 */



public class App {
    public String getGreeting() {
        return "she shuttle scheduler.";
    }

    public static void main(String[] args) {


        WorkflowMethods workflowMethods = new WorkflowMethods();
        ExcelWriter excelWriter = new ExcelWriter();
        FilterOutliers filterOutliers = new FilterOutliers();
        ReadAllRoutes readAllRoutes = new ReadAllRoutes();
        ScheduleFlow scheduler = new ScheduleFlow();

        def fileList = []

        Properties properties = new Properties()


        this.getClass().getResource( '/application.properties' ).withInputStream {
            properties.load(it)
        }

        def dir = new File(properties."she.shuttle.scheduler.input".toString())

        System.out.println(new App().getGreeting());
        HashMap<Segment,List<Bucket>> segmentBuckets = new HashMap<>();
        HashMap<Segment,List<Bucket>> eachFileSegmentBuckets = new HashMap<>();

        dir.eachFile(FileType.FILES) { file ->
            if(file.name != ".DS_Store")
            fileList << file.path
        }
        fileList.each {
            println("computing file ${it}")
            eachFileSegmentBuckets = workflowMethods.readExcelData(it)
            segmentBuckets.putAll(eachFileSegmentBuckets)
        }

        filterOutliers.filter(segmentBuckets);
        excelWriter.createOutputExcel(segmentBuckets);
        Routes availableRoutes = readAllRoutes.readAllRoutesFromExcel();
        scheduler.startScheduleWorkflow(availableRoutes,segmentBuckets);
    }
}
